Update headers on rest response (issue with CORS)
ASUWebPlatforms/asu-isearch pull request #132
Opened 2022-03-04 16:04 UTC by duarte-daniela

2022-03-04 19:14 UTC, mlsamuelson requested changes

2022-03-04 19:14 UTC, mlsamuelson commented on web/modules/custom/webdir_api/src/Plugin/rest/resource/WebDirectoryProfileAffiliationsResource.php
> +        $status_code = 500;
@duarte-daniela For these cases, I think a 404 Not Found is a better response: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

2022-03-07 09:07 UTC, duarte-daniela commented on web/modules/custom/webdir_api/src/Plugin/rest/resource/WebDirectoryProfileAffiliationsResource.php
> +        $status_code = 500;
@mlsamuelson Done!

2022-03-07 17:07 UTC, mlsamuelson approved these changes

2022-03-07 17:08 UTC, merged