ASUIS-330: Start determining if a profile is a student.
ASUWebPlatforms/asu-isearch pull request #158
Opened 2022-03-28 05:24 UTC by georgebaev

2022-03-29 19:46 UTC, mlsamuelson approved these changes

2022-03-29 21:32 UTC, mlsamuelson requested changes
@georgebaev I didn't see any issues with the code, but when testing on the site created by the CI, some pages are throwing errors, such as https://pr-158-asu-isearch.ws.asu.edu/user/2 while others (many admin UI pages) do not. It makes me suspect in some cases there are fatal errors happening with these checks. Can you look into it before this is approved?

2022-03-30 05:08 UTC, georgebaev commented
@mlsamuelson the error was thrown when no ASURITE ID exist for the profile. This is fixed now.

2022-03-30 14:38 UTC, mlsamuelson approved these changes
@georgebaev Perfect! Looks good now. Thank you.

2022-03-30 14:38 UTC, merged