ASUIS-346: Fix User form grammar.
ASUWebPlatforms/asu-isearch pull request #169
Opened 2022-04-02 12:10 UTC by georgebaev

2022-04-04 18:26 UTC, mlsamuelson commented on web/modules/custom/webdir_profile/js/webdir-profile.js
> +   * Profile related JavaScript functioality.
Typo: `functioality` should be `functionality`.

2022-04-04 18:28 UTC, mlsamuelson requested changes

2022-04-04 18:28 UTC, mlsamuelson commented on config/field.field.user.user.user_picture.yml
>  required: false
Comma added in this line should be removed - no comma after GIF in: `JPEG, JPG, GIF or PNG`
This is in compliance with Brand Guide Standards: https://brandguide.asu.edu/brand-elements/writing-content/punctuation#:~:text=ASU%20style%20does%20not%20recognize,is%20red%2C%20white%20and%20blue.

2022-04-05 04:04 UTC, georgebaev commented on config/field.field.user.user.user_picture.yml
>  required: false
This is fixed

2022-04-05 04:04 UTC, georgebaev commented on web/modules/custom/webdir_profile/js/webdir-profile.js
> +   * Profile related JavaScript functioality.
This is fixed.

2022-04-05 14:40 UTC, mlsamuelson approved these changes

2022-04-05 14:40 UTC, merged